include:
  - project: "widas/codequality"
    ref: master
    file: "ci_templates/php8.gitlab-ci.yml"

stages:
  - test
  - badges
  - deploy
  - publish

github_sync:
  stage: publish
  image: bitnami/git
  script:
    - git config --global --add safe.directory $PWD
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email $GITLAB_USER_EMAIL
    - git checkout master
    - git remote -v >> temp
    - if grep -q github temp;then echo 'remote github already exists';else git remote add github https://github.com/Cidaas/cidaas-sdk-php.git;fi
    - |
      OBJECTS="Dockerfile .gitlab-ci.yml scripts temp docker docker-compose.yml run-php-docker.sh Jenkinsfile"
      for File in $OBJECTS
      do
        if grep -Fxq $File .gitignore;then echo "do nothing";else echo "$File" >> .gitignore;fi
      done
    - git add . && git commit -m "fix():update gitignore" && git status
    - ls
    - git push https://$USER:$PAT@github.com/Cidaas/cidaas-sdk-php.git HEAD:master -f
  only:
    - master
  when: manual
