include:
  - project: "widas/codequality"
    ref: master
    file: "ci_templates/php8.gitlab-ci.yml"

stages:
  - test
  - badges
  - deploy
  - release
  - publish

codecoverage:
  image: php:fpm-alpine
  before_script:
    - apk add --no-cache tar=1.35-r2 git zip unzip $PHPIZE_DEPS linux-headers
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-text | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" > coverage_report.txt
  coverage: '/total:\s+\(statements\)\s+(\d+(?:\.\d+)?%)/'
  artifacts:
    paths: [coverage_report.txt]


create_codequality_badges:
  rules:
    - when: never

pages:
  before_script:
    - mkdir public

release:
  image: docker-registry.widas.de:5050/dockerregistry/common/semantic-release:v1.0.5
  stage: release
  script:
    - semantic-release
  only:
    - master
    - /^hotfix.*$/
    - /^release-v.*$/

github_sync:
  stage: publish
  image: bitnami/git
  script:
    - git config --global --add safe.directory $PWD
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email $GITLAB_USER_EMAIL
    - git checkout master
    - git remote -v >> temp
    - if grep -q github temp;then echo 'remote github already exists';else git remote add github https://github.com/Cidaas/cidaas-sdk-php.git;fi
    - |
      OBJECTS="Dockerfile .gitlab-ci.yml scripts temp docker docker-compose.yml run-php-docker.sh Jenkinsfile public codeclimate.html gl-code-quality-report.json"
      ISFILECHANGED=false
      for FILE in $OBJECTS
      do
        if grep -Fxq $FILE .gitignore;
        then echo "do nothing";
        else echo "$FILE" >> .gitignore;
        ISFILECHANGED=true
        fi
      done
      if $ISFILECHANGED;
      then
        git add .gitignore;
        git commit -m "fix(): cleanup";
        git rm -r --cached .;
        git add .;
        git commit -m "fix(): gitignore update"
      fi
    - git push https://$USER:$PAT@github.com/Cidaas/cidaas-sdk-php.git HEAD:master -f
  only:
    - master
  when: manual
